### ISSUE TITLE
Some issues about the paper

### ISSUE THREAD

**Issue by youweixiansheng** [panpanfei/Dual-Pixel-Exploration-Simultaneous-Depth-Estimation-and-Image-Restoration#1]
Hi, thanks for your inspired work, I have some issues about the experiments in the paper.
 In Table 1, the result of the DPDNet is reported as 25.53 in DPD-blur dataset. However, the original paper given 25.13.  So is the SSIM(0.826/0.786). Can you explain it? Thank you!

**Comment by panpanfei** [comment]
Hi, the resolution of testing images used in their and our experiment is different.

**Comment by liyucs** [comment]
May I ask what image resolution is used for DPD-blur testset? Thank you very much!
