### ISSUE TITLE
generatedpimage(RGB_img,disp) returns two values instead of three

### ISSUE THREAD

**Issue by ramazanabd** [panpanfei/Dual-Pixel-Exploration-Simultaneous-Depth-Estimation-and-Image-Restoration#6]
In the simulator_dp_nyu_testingdata.m and simulator_dp_nyu_trainingdata.m, there's a line:

**[img_left,img_right,disp_left] = generatedpimage(RGB_img,disp);**

which gives an error *"Too many output arguments."*. In simulator_dp_main.m, the line is like this

**[img_left,img_right] = generatedpimage(RGB_img,disp);**

Could you clarify if generatedpimage.p was updated to return 3 values, but not updated in github? or what is the problem?

Thank you!

**Comment by panpanfei** [comment]
Hi Thanks, already fixed.
