### ISSUE TITLE
May I ask what image resolution is used for DPD-blur testset? Thank you very much!

### ISSUE THREAD

**Issue by panpanfei** [panpanfei/Dual-Pixel-Exploration-Simultaneous-Depth-Estimation-and-Image-Restoration#7]
May I ask what image resolution is used for DPD-blur testset? Thank you very much!

_Originally posted by @liyucs in https://github.com/panpanfei/Dual-Pixel-Exploration-Simultaneous-Depth-Estimation-and-Image-Restoration/issues/1#issuecomment-909215523_

**Comment by panpanfei** [comment]
For the original resolution, our result is 25.4136 / 0.8394 in PSNR/SSIM.

In our paper, the reported result is for images with half resolution of the original images.

**Comment by liyucs** [comment]
Thank you for the reply!
